# Generated by Django 4.1.1 on 2022-09-30 16:18

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[
                student.validators.ValidEmailDomain('@gmail.com', '@yahoo.com', '@icloud.com')]),
        ),
    ]
